CREATE TABLE
    IF NOT EXISTS user (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(255) NOT NULL UNIQUE,
        magic_link VARCHAR(255) DEFAULT NULL UNIQUE
    );

CREATE TABLE
    IF NOT EXISTS NFT (
        id INT AUTO_INCREMENT PRIMARY KEY,
        userId INT NOT NULL,
        address VARCHAR(255) NOT NULL,
        withdrawn BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE
    );